### ISSUE TITLE
Could not locate nacl lib

### ISSUE THREAD

**Issue by dmachard** [dmachard/dnsdist-console#1]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/automation/.local/lib/python3.9/site-packages/dnsdist_console/__init__.py", line 1, in <module>
    from dnsdist_console.console import Console
  File "/home/automation/.local/lib/python3.9/site-packages/dnsdist_console/console.py", line 3, in <module>
    import libnacl
  File "/home/automation/.local/lib/python3.9/site-packages/libnacl/__init__.py", line 83, in <module>
    nacl = _get_nacl()
  File "/home/automation/.local/lib/python3.9/site-packages/libnacl/__init__.py", line 79, in _get_nacl
    raise OSError(msg)
OSError: Could not locate nacl lib, searched for libsodium.so, libsodium.so.23, libsodium.so.18, libsodium.so.17, libsodium.so.13, libsodium.so.10, libsodium.so.5, libsodium.so.4,

**Comment by dmachard** [comment]
solution => install libsodium

sudo dnf install libsodium
